services:
  johnny-castaway:
    build: .
    container_name: johnny-tv
    environment:
      - SCR_PATH=/host_media/johnnycastaway.exe
    volumes:
      - C:/Users/jthom/Downloads:/host_media:ro
    ports:
      - "9081:9081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '0.50'
