services:
  johnny-castaway:
    build: .
    container_name: johnny-tv
    environment:
      # Point this to wherever the file lives on your host machine
      - SCR_PATH=/mnt/media/screensavers/jc15.exe
    volumes:
      - /mnt/media/screensavers:/host_media:ro
    ports:
      - "9081:9081"
    restart: unless-stopped
